=== Qucs/qucs/qucs-core/deps/adms/admst.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
     This dtd describes the basic data structures used by admst transforms
     You can try using xmllint: xmllint myadmstscript.xml -noout -postvalid -noblanks
--> 
<!--
  $Id: admst.dtd 1176 2008-12-04 15:02:59Z r29173 $
-->
<!--
  $Log$
  Revision 1.4  2005/09/14 15:41:31  r29173
  renamed admst:templates to admst:template (same for apply-template)

  Revision 1.3  2005/08/18 10:45:23  r29173
  renamed admst:choice to admst:choose (admst:choice tolerated)

  Revision 1.2  2005/03/31 18:12:00  r29173
  migration to adms-2.x.x: converted to adms2 syntax

  Revision 1.6  2005/03/22 11:30:18  r29173
  migration to adms-2.x.x: clean-up xml constructs

  Revision 1.5  2005/03/17 08:26:28  r29173
  migration to adms-2.x.x: move all href from absolute to relative values

  Revision 1.4  2005/02/25 12:49:35  r29173
  migration to adms-2.x.x: renamed admst transforms

-->

<!ENTITY % anyadmst '#PCDATA|admst:return|admst:fatal|admst:warning|admst:count|admst:choose|admst:copy|admst:getenv|admst:setenv|admst:open|admst:templates|admst:template|admst:if-inside|admst:if-not-inside|admst:differentiate|admst:push|admst:reverse|admst:value-of|admst:new|admst:for-each|admst:reset|admst:if|admst:assert|admst:text|admst:apply-template|admst:apply-templates|admst:join|admst:message|admst:error|admst:value-to|admst:variable|admst:read'>

<!ELEMENT admst (%anyadmst;)*>
<!ATTLIST admst version CDATA #IMPLIED>
<!ATTLIST admst xmlns:admst CDATA #IMPLIED>
<!ATTLIST admst xmlns:m CDATA #IMPLIED>
<!ATTLIST admst xmlns:html CDATA #IMPLIED>

<!ELEMENT admst:count EMPTY>
<!ATTLIST admst:count select CDATA #REQUIRED>

<!ELEMENT admst:return EMPTY>
<!ATTLIST admst:return name CDATA #REQUIRED>
<!ATTLIST admst:return value CDATA #REQUIRED>

<!ELEMENT admst:choose (admst:when+,admst:otherwise?)>
<!ELEMENT admst:when (%anyadmst;)*>
<!ATTLIST admst:when test CDATA #REQUIRED>
<!ELEMENT admst:otherwise (%anyadmst;)*>

<!ELEMENT admst:open (%anyadmst;)*>
<!ATTLIST admst:open file CDATA #REQUIRED>

<!ELEMENT admst:copy EMPTY>
<!ATTLIST admst:copy from CDATA #REQUIRED>
<!ATTLIST admst:copy to CDATA #REQUIRED>

<!ELEMENT admst:getenv EMPTY>
<!ATTLIST admst:getenv name CDATA #REQUIRED>

<!ELEMENT admst:setenv EMPTY>
<!ATTLIST admst:setenv name CDATA #REQUIRED>
<!ATTLIST admst:setenv value CDATA #REQUIRED>

<!ELEMENT admst:error EMPTY>
<!ATTLIST admst:error format CDATA #IMPLIED>
<!ATTLIST admst:error test CDATA #IMPLIED>

<!ELEMENT admst:warning EMPTY>
<!ATTLIST admst:warning format CDATA #IMPLIED>
<!ATTLIST admst:warning test CDATA #IMPLIED>

<!ELEMENT admst:message EMPTY>
<!ATTLIST admst:message format CDATA #IMPLIED>
<!ATTLIST admst:message test CDATA #IMPLIED>

<!ELEMENT admst:fatal EMPTY>
<!ATTLIST admst:fatal format CDATA #IMPLIED>
<!ATTLIST admst:fatal test CDATA #IMPLIED>

<!ELEMENT admst:reset EMPTY>
<!ATTLIST admst:reset select CDATA #REQUIRED>

<!ELEMENT admst:for-each (%anyadmst;)*>
<!ATTLIST admst:for-each select CDATA #REQUIRED>

<!ELEMENT admst:templates (%anyadmst;)*>
<!ATTLIST admst:templates mode CDATA #IMPLIED>
<!ATTLIST admst:templates match CDATA #IMPLIED>
<!ELEMENT admst:template (%anyadmst;)*>
<!ATTLIST admst:template mode CDATA #IMPLIED>
<!ATTLIST admst:template match CDATA #IMPLIED>

<!ELEMENT admst:new (%anyadmst;)*>
<!ATTLIST admst:new datatype CDATA #IMPLIED>
<!ATTLIST admst:new arguments CDATA #IMPLIED>
<!ATTLIST admst:new inputs CDATA #IMPLIED>
<!ATTLIST admst:new test CDATA #IMPLIED>

<!ELEMENT admst:if (%anyadmst;)*>
<!ATTLIST admst:if test CDATA #IMPLIED>

<!ELEMENT admst:read EMPTY>
<!ATTLIST admst:read file CDATA #IMPLIED>

<!ELEMENT admst:push EMPTY>
<!ATTLIST admst:push into CDATA #IMPLIED>
<!ATTLIST admst:push select CDATA #REQUIRED>
<!ATTLIST admst:push test CDATA #IMPLIED>
<!ATTLIST admst:push onduplicate CDATA #IMPLIED>
<!ATTLIST admst:push oncompare CDATA #IMPLIED>

<!ELEMENT admst:variable EMPTY>
<!ATTLIST admst:variable name CDATA #REQUIRED>
<!ATTLIST admst:variable value CDATA #IMPLIED>
<!ATTLIST admst:variable string CDATA #IMPLIED>
<!ATTLIST admst:variable select CDATA #IMPLIED>
<!ATTLIST admst:variable test CDATA #IMPLIED>
<!ATTLIST admst:variable path CDATA #IMPLIED>

<!ELEMENT admst:value-to EMPTY>
<!ATTLIST admst:value-to select CDATA #REQUIRED>
<!ATTLIST admst:value-to value CDATA #IMPLIED>
<!ATTLIST admst:value-to string CDATA #IMPLIED>
<!ATTLIST admst:value-to test CDATA #IMPLIED>
<!ATTLIST admst:value-to path CDATA #IMPLIED>

<!ELEMENT admst:differentiate EMPTY>
<!ATTLIST admst:differentiate select CDATA #REQUIRED>
<!ATTLIST admst:differentiate probe CDATA #IMPLIED>

<!ELEMENT admst:apply-templates (%anyadmst;)*>
<!ATTLIST admst:apply-templates select CDATA #REQUIRED>
<!ATTLIST admst:apply-templates required (yes|no) "yes">
<!ATTLIST admst:apply-templates match CDATA #IMPLIED>
<!ATTLIST admst:apply-templates test CDATA #IMPLIED>

<!ELEMENT admst:text EMPTY>
<!ATTLIST admst:text format CDATA #IMPLIED>
<!ATTLIST admst:text select CDATA #IMPLIED>
<!ATTLIST admst:text test CDATA #IMPLIED>

<!ELEMENT admst:value-of EMPTY>
<!ATTLIST admst:value-of select CDATA #REQUIRED>

<!ELEMENT admst:reverse EMPTY>
<!ATTLIST admst:reverse select CDATA #REQUIRED>

<!ELEMENT admst:if-inside (%anyadmst;)*>
<!ATTLIST admst:if-inside test CDATA #IMPLIED>
<!ATTLIST admst:if-inside list CDATA #IMPLIED>
<!ATTLIST admst:if-inside select CDATA #IMPLIED>

<!ELEMENT admst:if-not-inside (%anyadmst;)*>
<!ATTLIST admst:if-not-inside test CDATA #IMPLIED>
<!ATTLIST admst:if-not-inside list CDATA #IMPLIED>
<!ATTLIST admst:if-not-inside select CDATA #IMPLIED>

<!ELEMENT admst:assert EMPTY>
<!ATTLIST admst:assert test CDATA #IMPLIED>
<!ATTLIST admst:assert format CDATA #IMPLIED>
<!ATTLIST admst:assert select CDATA #IMPLIED>

<!ELEMENT admst:join (%anyadmst;)*>
<!ATTLIST admst:join select CDATA #REQUIRED>
<!ATTLIST admst:join separator CDATA #IMPLIED>

=== Qucs/qucs/qucs-core/deps/adms/scripts/sort.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE admst PUBLIC "-//adms//DTD admst 2.0//-" "http://mot-adms.sourceforge.net/xml-files/adms/admst.dtd">
<!--
  Usage: admsXml -e sort.xml
  Description: create file sort.va, then gives different usages of sort() and reverse()
-->
<!--
  $Id: getinstance.xml 505 2007-01-23 11:17:43Z r29173 $
  $Log$
  Revision 1.7  2006/03/23 13:46:44  r29173
  cosmetic changes

  Revision 1.4  2006/03/23 07:51:39  r29173
  fixed bug in computation of ddx
-->

<admst version="2.3.0" xmlns:admst="http://mot-adms.svn.sourceforge.net/viewvc/*checkout*/mot-adms/trunk/adms/admst.dtd">
  <!-- create file sort.va -->
  <admst:variable name="module1" select="index"/>
  <admst:open file="$(module1).va">
`include &quot;discipline.h&quot;
module $(module1)(p,n);
  inout p, n;
  electrical p, n;
  parameter real B=1.0;
  parameter real A=1.0;
  real b,a;
  analog a=1;
endmodule
  </admst:open>
  <admst:message format="$(module1).va: file created\n"/>
  <admst:read file="$(module1).va"/>
  <admst:apply-templates select="module[name='$(module1)']" match="adms.implicit.xml.module"/>
  <!-- test sort() and reverse() -->
  <admst:for-each select="/module">
  01 ** foreach(variable) text................................@returns (B,A,b,a)
    <admst:text format=" "/>
    <admst:for-each select="variable"><admst:text format="%(.),"/></admst:for-each>
    <admst:text format=" "/>
    <admst:for-each select="variable"><admst:text format="%(position(.)).%(index(../variable,.)) "/></admst:for-each>
  02 ** foreach.sort(variable) text...........................@returns (A,B,a,b)
    <admst:text format=" "/>
    <admst:for-each select="sort(variable)"><admst:text format="%(.),"/></admst:for-each>
    <admst:text format=" "/>
    <admst:for-each select="sort(variable)"><admst:text format="%(position(.)).%(index(../variable,.)) "/></admst:for-each>
  03 ** \$p1=variable text(\$p1)................................@returns (B,A,b,a)
    <admst:variable name="p1" path="variable"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(position(.)).%(index($p1,.)) "/>
  04 ** \$p1=sort(variable) text(\$p1)..........................@returns (A,B,a,b)
    <admst:variable name="p1" path="sort(variable)"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(position(.)).%(index($p1,.)) "/>
  05 ** text(variable)........................................@returns (B,A,b,a)
    <admst:text format=" "/>
    <admst:text select="variable" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="variable" format="%(position(.)).%(index(../variable,.)) "/>
  06 ** text(sort(variable))..................................@returns (A,B,a,b)
    <admst:text format=" "/>
    <admst:text select="sort(variable)" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="sort(variable)" format="%(position(.)).%(index(../variable,.)) "/>
  07 ** foreach(reverse(variable))............................@returns (a,b,A,B)
    <admst:text format=" "/>
    <admst:for-each select="reverse(variable)"><admst:text format="%(.),"/></admst:for-each>
    <admst:text format=" "/>
    <admst:for-each select="reverse(variable)"><admst:text format="%(position(.)).%(index(../variable,.)) "/></admst:for-each>
  08 ** \$p1=variable text(reverse(\$p1)).......................@returns (a,b,A,B)
    <admst:variable name="p1" path="variable"/>
    <admst:text format=" "/>
    <admst:text select="reverse($p1)" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="reverse($p1)" format="%(position(.)).%(index($p1,.)) "/>
  09 ** \$p1=reverse(variable) text(\$p1).......................@returns (a,b,A,B)
    <admst:variable name="p1" path="reverse(variable)"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(position(.)).%(index($p1,.)) "/>
  10 ** reset(\$p1) push(\$p1,variable[input='no']) text(\$p1)...@returns (a,b)
    <admst:variable name="p1"/>
    <admst:push into="$p1" select="variable[input='no']"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(position(.)).%(index($p1,.)) "/>
  11 ** \$p2=reverse(sort(\$p1)) text(\$p2)......................@returns (b,a)
    <admst:variable name="p2" path="reverse(sort($p1))"/>
    <admst:text format=" "/>
    <admst:text select="$p2" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="$p2" format="%(position(.)).%(index($p2,.)) "/>
  12 ** push(\$p1,variable) text(\$p1)..........................@returns (a,b,A,B,a,b)
    <admst:push into="$p1" select="variable"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="$p1" format="%(position(.)).%(index($p1,.)) "/>
  13 ** text(sort(reverse(\$p1)))..............................@returns (A,B,a,a,b,b)
    <admst:text format=" "/>
    <admst:text select="sort(reverse($p1))" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="sort(reverse($p1))" format="%(position(.)).%(index($p1,.)) "/>
  14 ** reset(\$p3) push(\$p3,\$p2) push(\$p3,\$p1) text(\$p1)......@returns (b,a,B,A,b,a,a,b)
    <admst:variable name="p3"/>
    <admst:push into="$p3" select="$p2"/>
    <admst:push into="$p3" select="$p1"/>
    <admst:text format=" "/>
    <admst:text select="$p3" format="%(.),"/>
    <admst:text format=" "/>
    <admst:text select="$p3" format="%(position(.)).%(index($p1,.)) "/>
    <admst:text format="\n"/>
  </admst:for-each>
  <admst:open file="target">
  01 ** foreach(variable) text................................@returns (B,A,b,a) B,A,b,a, 1.0 2.1 3.2 4.3
  02 ** foreach.sort(variable) text...........................@returns (A,B,a,b) A,B,a,b, 1.1 2.0 3.3 4.2
  03 ** \$p1=variable text(\$p1)................................@returns (B,A,b,a) B,A,b,a, 1.0 2.1 3.2 4.3
  04 ** \$p1=sort(variable) text(\$p1)..........................@returns (A,B,a,b) A,B,a,b, 1.0 2.1 3.2 4.3
  05 ** text(variable)........................................@returns (B,A,b,a) B,A,b,a, 1.0 2.1 3.2 4.3
  06 ** text(sort(variable))..................................@returns (A,B,a,b) A,B,a,b, 1.1 2.0 3.3 4.2
  07 ** foreach(reverse(variable))............................@returns (a,b,A,B) a,b,A,B, 1.3 2.2 3.1 4.0
  08 ** \$p1=variable text(reverse(\$p1)).......................@returns (a,b,A,B) a,b,A,B, 1.3 2.2 3.1 4.0
  09 ** \$p1=reverse(variable) text(\$p1).......................@returns (a,b,A,B) a,b,A,B, 1.0 2.1 3.2 4.3
  10 ** reset(\$p1) push(\$p1,variable[input='no']) text(\$p1)...@returns (a,b) a,b, 1.0 2.1
  11 ** \$p2=reverse(sort(\$p1)) text(\$p2)......................@returns (b,a) b,a, 1.0 2.1
  12 ** push(\$p1,variable) text(\$p1)..........................@returns (a,b,A,B,a,b) a,b,A,B,a,b, 1.0 2.1 3.2 4.3 5.0 6.1
  13 ** text(sort(reverse(\$p1)))..............................@returns (A,B,a,a,b,b) A,B,a,a,b,b, 1.2 2.3 3.0 4.0 5.1 6.1
  14 ** reset(\$p3) push(\$p3,\$p2) push(\$p3,\$p1) text(\$p1)......@returns (b,a,B,A,b,a,a,b) b,a,B,A,b,a,a,b, 1.1 2.0 3.3 4.2 5.1 6.0 7.0 8.1
  </admst:open>
  <admst:message format="target: file created\n"/>
</admst>

=== Qucs/qucs/qucs-core/deps/adms/scripts/arobavariable.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE admst PUBLIC "-//adms//DTD admst 2.0//-" "http://mot-adms.sourceforge.net/xml-files/adms/admst.dtd">
<!--
  Usage: admsXml -e arobavariable.xml
  Description: create file arobavariable.va, then test implementation of @... construct
-->
<!--
  $Id: getinstance.xml 505 2007-01-23 11:17:43Z r29173 $
  $Log$
-->

<admst version="2.3.0"  xmlns:admst="http://mot-adms.svn.sourceforge.net/viewvc/*checkout*/mot-adms/trunk/adms/admst.dtd">
  <!-- create file arobavariable.va -->
  <admst:variable name="module1" select="arobavariable"/>
  <admst:open file="$(module1).va">
`include &quot;discipline.h&quot;
module $(module1)(p,n);
  inout p, n;
  electrical p, n;
  parameter real A=1.0;
  parameter real B=1.0;
  real a,b;
  analog
  begin
    begin : A
      real a,b;
      a=1;
      b=1;
    end
    begin : B
      a=1;
      b=1;
    end
  end
endmodule
  </admst:open>
  <admst:message format="$(module1).va: file created\n"/>
  <admst:read file="$(module1).va"/>
  <admst:apply-templates select="module[name='$(module1)']" match="adms.implicit.xml.module"/>
  <!-- test @... construct -->
  <admst:template match="iterate">
    <admst:push into="@(%(upper-case(module)))" select="module"/>
    <admst:push into="@scope" select="block/name"/>
    <admst:push into="@itself" select="."/>
    <admst:text format="set %(@(%(upper-case(module)))).%(@scope).%(@itself)\n"/>
  </admst:template>
  <admst:for-each select="/module/assignment">
    <admst:apply-templates select="lhs" match="iterate"/>
  </admst:for-each>
  <admst:text select="/module/assignment/lhs" format="check %(@AROBAVARIABLE/datatypename).%(@scope).%(@itself)\n"/>
</admst>
