=== Qucs/qucs/qucs-core/deps/adms/admst.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
     This dtd describes the basic data structures used by admst transforms
     You can try using xmllint: xmllint myadmstscript.xml -noout -postvalid -noblanks
--> 
<!--
  $Id: admst.dtd 1176 2008-12-04 15:02:59Z r29173 $
-->
<!--
  $Log$
  Revision 1.4  2005/09/14 15:41:31  r29173
  renamed admst:templates to admst:template (same for apply-template)

  Revision 1.3  2005/08/18 10:45:23  r29173
  renamed admst:choice to admst:choose (admst:choice tolerated)

  Revision 1.2  2005/03/31 18:12:00  r29173
  migration to adms-2.x.x: converted to adms2 syntax

  Revision 1.6  2005/03/22 11:30:18  r29173
  migration to adms-2.x.x: clean-up xml constructs

  Revision 1.5  2005/03/17 08:26:28  r29173
  migration to adms-2.x.x: move all href from absolute to relative values

  Revision 1.4  2005/02/25 12:49:35  r29173
  migration to adms-2.x.x: renamed admst transforms

-->

<!ENTITY % anyadmst '#PCDATA|admst:return|admst:fatal|admst:warning|admst:count|admst:choose|admst:copy|admst:getenv|admst:setenv|admst:open|admst:templates|admst:template|admst:if-inside|admst:if-not-inside|admst:differentiate|admst:push|admst:reverse|admst:value-of|admst:new|admst:for-each|admst:reset|admst:if|admst:assert|admst:text|admst:apply-template|admst:apply-templates|admst:join|admst:message|admst:error|admst:value-to|admst:variable|admst:read'>

<!ELEMENT admst (%anyadmst;)*>
<!ATTLIST admst version CDATA #IMPLIED>
<!ATTLIST admst xmlns:admst CDATA #IMPLIED>
<!ATTLIST admst xmlns:m CDATA #IMPLIED>
<!ATTLIST admst xmlns:html CDATA #IMPLIED>

<!ELEMENT admst:count EMPTY>
<!ATTLIST admst:count select CDATA #REQUIRED>

<!ELEMENT admst:return EMPTY>
<!ATTLIST admst:return name CDATA #REQUIRED>
<!ATTLIST admst:return value CDATA #REQUIRED>

<!ELEMENT admst:choose (admst:when+,admst:otherwise?)>
<!ELEMENT admst:when (%anyadmst;)*>
<!ATTLIST admst:when test CDATA #REQUIRED>
<!ELEMENT admst:otherwise (%anyadmst;)*>

<!ELEMENT admst:open (%anyadmst;)*>
<!ATTLIST admst:open file CDATA #REQUIRED>

<!ELEMENT admst:copy EMPTY>
<!ATTLIST admst:copy from CDATA #REQUIRED>
<!ATTLIST admst:copy to CDATA #REQUIRED>

<!ELEMENT admst:getenv EMPTY>
<!ATTLIST admst:getenv name CDATA #REQUIRED>

<!ELEMENT admst:setenv EMPTY>
<!ATTLIST admst:setenv name CDATA #REQUIRED>
<!ATTLIST admst:setenv value CDATA #REQUIRED>

<!ELEMENT admst:error EMPTY>
<!ATTLIST admst:error format CDATA #IMPLIED>
<!ATTLIST admst:error test CDATA #IMPLIED>

<!ELEMENT admst:warning EMPTY>
<!ATTLIST admst:warning format CDATA #IMPLIED>
<!ATTLIST admst:warning test CDATA #IMPLIED>

<!ELEMENT admst:message EMPTY>
<!ATTLIST admst:message format CDATA #IMPLIED>
<!ATTLIST admst:message test CDATA #IMPLIED>

<!ELEMENT admst:fatal EMPTY>
<!ATTLIST admst:fatal format CDATA #IMPLIED>
<!ATTLIST admst:fatal test CDATA #IMPLIED>

<!ELEMENT admst:reset EMPTY>
<!ATTLIST admst:reset select CDATA #REQUIRED>

<!ELEMENT admst:for-each (%anyadmst;)*>
<!ATTLIST admst:for-each select CDATA #REQUIRED>

<!ELEMENT admst:templates (%anyadmst;)*>
<!ATTLIST admst:templates mode CDATA #IMPLIED>
<!ATTLIST admst:templates match CDATA #IMPLIED>
<!ELEMENT admst:template (%anyadmst;)*>
<!ATTLIST admst:template mode CDATA #IMPLIED>
<!ATTLIST admst:template match CDATA #IMPLIED>

<!ELEMENT admst:new (%anyadmst;)*>
<!ATTLIST admst:new datatype CDATA #IMPLIED>
<!ATTLIST admst:new arguments CDATA #IMPLIED>
<!ATTLIST admst:new inputs CDATA #IMPLIED>
<!ATTLIST admst:new test CDATA #IMPLIED>

<!ELEMENT admst:if (%anyadmst;)*>
<!ATTLIST admst:if test CDATA #IMPLIED>

<!ELEMENT admst:read EMPTY>
<!ATTLIST admst:read file CDATA #IMPLIED>

<!ELEMENT admst:push EMPTY>
<!ATTLIST admst:push into CDATA #IMPLIED>
<!ATTLIST admst:push select CDATA #REQUIRED>
<!ATTLIST admst:push test CDATA #IMPLIED>
<!ATTLIST admst:push onduplicate CDATA #IMPLIED>
<!ATTLIST admst:push oncompare CDATA #IMPLIED>

<!ELEMENT admst:variable EMPTY>
<!ATTLIST admst:variable name CDATA #REQUIRED>
<!ATTLIST admst:variable value CDATA #IMPLIED>
<!ATTLIST admst:variable string CDATA #IMPLIED>
<!ATTLIST admst:variable select CDATA #IMPLIED>
<!ATTLIST admst:variable test CDATA #IMPLIED>
<!ATTLIST admst:variable path CDATA #IMPLIED>

<!ELEMENT admst:value-to EMPTY>
<!ATTLIST admst:value-to select CDATA #REQUIRED>
<!ATTLIST admst:value-to value CDATA #IMPLIED>
<!ATTLIST admst:value-to string CDATA #IMPLIED>
<!ATTLIST admst:value-to test CDATA #IMPLIED>
<!ATTLIST admst:value-to path CDATA #IMPLIED>

<!ELEMENT admst:differentiate EMPTY>
<!ATTLIST admst:differentiate select CDATA #REQUIRED>
<!ATTLIST admst:differentiate probe CDATA #IMPLIED>

<!ELEMENT admst:apply-templates (%anyadmst;)*>
<!ATTLIST admst:apply-templates select CDATA #REQUIRED>
<!ATTLIST admst:apply-templates required (yes|no) "yes">
<!ATTLIST admst:apply-templates match CDATA #IMPLIED>
<!ATTLIST admst:apply-templates test CDATA #IMPLIED>

<!ELEMENT admst:text EMPTY>
<!ATTLIST admst:text format CDATA #IMPLIED>
<!ATTLIST admst:text select CDATA #IMPLIED>
<!ATTLIST admst:text test CDATA #IMPLIED>

<!ELEMENT admst:value-of EMPTY>
<!ATTLIST admst:value-of select CDATA #REQUIRED>

<!ELEMENT admst:reverse EMPTY>
<!ATTLIST admst:reverse select CDATA #REQUIRED>

<!ELEMENT admst:if-inside (%anyadmst;)*>
<!ATTLIST admst:if-inside test CDATA #IMPLIED>
<!ATTLIST admst:if-inside list CDATA #IMPLIED>
<!ATTLIST admst:if-inside select CDATA #IMPLIED>

<!ELEMENT admst:if-not-inside (%anyadmst;)*>
<!ATTLIST admst:if-not-inside test CDATA #IMPLIED>
<!ATTLIST admst:if-not-inside list CDATA #IMPLIED>
<!ATTLIST admst:if-not-inside select CDATA #IMPLIED>

<!ELEMENT admst:assert EMPTY>
<!ATTLIST admst:assert test CDATA #IMPLIED>
<!ATTLIST admst:assert format CDATA #IMPLIED>
<!ATTLIST admst:assert select CDATA #IMPLIED>

<!ELEMENT admst:join (%anyadmst;)*>
<!ATTLIST admst:join select CDATA #REQUIRED>
<!ATTLIST admst:join separator CDATA #IMPLIED>

=== Qucs/qucs/qucs-core/deps/adms/scripts/croixvariable.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE admst PUBLIC "-//adms//DTD admst 2.0//-" "http://mot-adms.sourceforge.net/xml-files/adms/admst.dtd">
<!--
  Usage: admsXml -e croixvariable.xml
  Description: create file croixvariable.va, then test implementation of #... construct
-->
<!--
  $Id: getinstance.xml 505 2007-01-23 11:17:43Z r29173 $
  $Log$
-->

<admst version="2.3.0"  xmlns:admst="http://mot-adms.svn.sourceforge.net/viewvc/*checkout*/mot-adms/trunk/adms/admst.dtd">
  <!-- create file croixvariable.va -->
  <admst:variable name="module1" select="croixvariable"/>
  <admst:open file="$(module1).va">
`include &quot;discipline.h&quot;
module $(module1)(p,n);
  inout p, n;
  electrical p, n;
  parameter real A=1.0;
  parameter real B=1.0;
  real a,b;
  analog
  begin
    begin : Loc
      real a,b;
      (*eq="Eq.1"*) a=1;
      (*eq="Eq.2"*) b=1;
    end
    begin : Glob
      (*eq="Eq.1"*) a=1;
      (*eq="Eq.2"*) b=1;
    end
  end
endmodule
  </admst:open>
  <admst:message format="$(module1).va: file created\n"/>
  <admst:read file="$(module1).va"/>
  <admst:apply-templates select="module[name='$(module1)']" match="adms.implicit.xml.module"/>
  <!-- test #... construct -->
  <admst:template match="iterate">
    <admst:value-to select="#insource" path="../attribute[name='eq']/value"/>
    <admst:text format="set %(.)#insource=%(#insource)\n"/>
  </admst:template>
  <admst:apply-templates select="/module/reverse(assignment)/lhs" match="iterate"/>
  <admst:text select="/module/reverse(assignment)/lhs" format="check %(block/name):%(.)#insource=%(#insource)\n"/>
  <admst:value-to select="/#a" path="module/variable"/>
  <admst:text format="-- %(/#a/datatypename)\n"/>
</admst>

=== Qucs/qucs/qucs-core/deps/adms/scripts/admstvariables.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE admst PUBLIC "-//adms//DTD admst 2.0//-" "http://mot-adms.svn.sourceforge.net/viewvc/mot-adms/trunk/adms/admst.dtd" >
<!--
    Usage: admsXml -e admstvariables.xml
    This example gives some hints on how to use admst variables.
    There are two types of admst variables:
    1- global variables: they first occur outside any admst:template
       They are 'seen' by any admst:template
    2- local variables: they occur inside admst:template
    Variables are declared using:
    1- <admst:variable name="variable">
    or
    2- <admst:variable name="myvariable" select="<string>">
    or
    3- <admst:variable name="myvariable" select="%p">
    In 2- myvariable is a string.
    In 3- myvariable is a adms element.
    The value of admst variables is accessed through $myvariable or $(myvariable).
    Limitations (adms-2.2.0): $(anystring) doesn't work inside admstpath.
-->
<admst version="2.3.0" xmlns:admst="https://mot-adms.svn.sourceforge.net/viewvc/mot-adms/trunk/adms/admsstyle.xsl">

<admst:template match="globalvariable">
  <admst:text format="my global variable: $myglobalvariable_string\n"></admst:text>
  <admst:text format="\$myglobalvariable_pointer/name =&gt; %($myglobalvariable_pointer/name)\n"></admst:text>
  <admst:variable name="mylocalvariable" select="this is the value of \$mylocalvariable"></admst:variable>
  <admst:text format="\$myglobalvariable_string =&gt; $(myglobalvariable_string)\n"></admst:text>
  <admst:variable name="mylocalvariable" select="this is the value of \$mylocalvariable"></admst:variable>
  <admst:text format="\$mylocalvariable =&gt; $mylocalvariable\n"></admst:text>
</admst:template>

<!-- as string -->
<admst:variable name="myglobalvariable_string" select="this is the value of \$myglobalvariable"></admst:variable>
<!-- as adms element -->
<admst:variable name="myglobalvariable_pointer" path="."></admst:variable>
<admst:apply-templates select="." match="globalvariable"></admst:apply-templates>

</admst>

=== Qucs/qucs/qucs-core/src/components/verilog/qucsMODULEguiJSONsymbol.xml
<!--

  Copyright (C) 2006 Helene Parruitte <parruit@enseirb.fr>
  Copyright (C) 2006 Bertrand Ardouin <ardouin@xmodtech.com>
  Copyright (C) 2006, 2007, 2008 Stefan Jahn <stefan@lkcc.org>
  Copyright (C) 2014 Guilherme Brondani Torri <guitorri@gmail.com>


  This is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.

-->

<!-- This is a modified version of qusMODULEgui.xml, by Guilherme Brondani Torri -->
<!-- It transforms the Verilog-A parameters into a JSON model properties file loadable by Qucs -->

<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE admst PUBLIC "-//adms//DTD admst 2.0//-" "http://mot-adms.sourceforge.net/xml-files/adms/admst.dtd">
<admst version="2.3.0" xmlns:admst="http://mot-adms.sourceforge.net/xml-files/admst">

<!-- handling of expression -->
<admst:template match=":expression">
  <admst:value-of select="tree/adms/datatypename"/>
  <admst:apply-templates select="tree" match=":%s" required="yes"/>
</admst:template>

<admst:template match=":number">
  <admst:value-of select="value"/>
  <admst:choose>
    <admst:when test="[scalingunit='1']">%s</admst:when>
    <admst:when test="[scalingunit='E']">%sE</admst:when>
    <admst:when test="[scalingunit='P']">%sP</admst:when>
    <admst:when test="[scalingunit='T']">%sT</admst:when>
    <admst:when test="[scalingunit='G']">%sG</admst:when>
    <admst:when test="[scalingunit='M']">%sM</admst:when>
    <admst:when test="[scalingunit='k']">%sk</admst:when>
    <admst:when test="[scalingunit='h']">(%s*1.0e+2)</admst:when>
    <admst:when test="[scalingunit='D']">(%s*1.0e+1)</admst:when>
    <admst:when test="[scalingunit='d']">(%s*1.0e-1)</admst:when>
    <admst:when test="[scalingunit='c']">(%s*1.0e-2)</admst:when>
    <admst:when test="[scalingunit='m']">%sm</admst:when>
    <admst:when test="[scalingunit='u']">%su</admst:when>
    <admst:when test="[scalingunit='n']">%sn</admst:when>
    <admst:when test="[scalingunit='A']">(%s*1.0e-10)</admst:when>
    <admst:when test="[scalingunit='p']">%sp</admst:when>
    <admst:when test="[scalingunit='f']">%sf</admst:when>
    <admst:when test="[scalingunit='a']">%sa</admst:when>
    <admst:otherwise>
      <admst:value-of select="scalingunit"/>
      <admst:fatal format="%s%s: scaling unit not supported\n"/>
    </admst:otherwise>
  </admst:choose>
</admst:template>

<admst:template match=":mapply_unary">
  <admst:if test="[name='plus']"> <admst:text format="+"/> </admst:if>
  <admst:if test="[name='minus']"> <admst:text format="-"/> </admst:if>
  <admst:if test="[name='not']"> <admst:text format="!"/> </admst:if>
  <admst:if test="[name='bw_not']"> <admst:text format="~"/> </admst:if>
  <admst:value-of select="arg1/adms/datatypename"/>
  <admst:apply-templates select="arg1" match=":%s" required="yes"/>
</admst:template>

<admst:template match=":string">
  <admst:value-of select="value"/>%s
</admst:template>

<!-- recurse, return final value -->
<admst:template match=":variable">
  <!--admst:value-of select="name"/>%s-->
  <admst:apply-templates select="default" match=":expression"/>
</admst:template>

<!-- handling of device: starting point -->
<admst:for-each select="/module">

<!-- definition of variables -->
<admst:value-of select="name"/>
<admst:variable name="module" select="%s"/>
<admst:count select="node"/>
<admst:variable name="nbr_nodes" select="%s"/>
</admst:for-each>

<!-- no comments on JSON files
/*
 * $(module).json - device symbol implementations for $(module) dynamic module
 *
 * This is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 */
 -->
<admst:open file="$(module)_props.json">

<admst:text format="{\n  &quot;description&quot; : &quot;$module verilog device&quot;,\n"/>

<admst:for-each select="/module">

<!-- find temp and tnom parameters -->
<admst:variable name="tnom" string="none"/>
<admst:variable name="temp" string="none"/>
<admst:for-each select="variable">
  <admst:if test="[input='yes']">
    <admst:if test="[upper-case(name)='TNOM']">
      <admst:variable name="tnom" path="."/>
    </admst:if>
    <admst:if test="[upper-case(name)='TEMP']">
      <admst:variable name="temp" path="."/>
    </admst:if>
  </admst:if>
</admst:for-each>

<!-- extract Verilog-A parameter as model properties -->
<admst:text format="  &quot;property&quot; : [\n"/>

<admst:for-each select="variable">
  <admst:if test="[input='yes']">
    <admst:value-of select="name"/>
    <admst:text format="    { &quot;name&quot; : &quot;%s&quot;, &quot;value&quot; : &quot;"/>
    <admst:apply-templates select="default" match=":expression"/>
    <admst:text format="&quot;, &quot;display&quot; : &quot;false&quot;, &quot;desc&quot; : "/>
    <admst:choose>
      <admst:when test="attribute[name='info']">
        <admst:value-of select="attribute[name='info']/value"/>
	<admst:text format="&quot;(%s)&quot;, "/>
      </admst:when>
      <admst:when test="attribute[name='desc']">
        <admst:value-of select="attribute[name='desc']/value"/>
	<admst:text format="&quot;(%s),&quot;, "/>
      </admst:when>
      <admst:when test="attribute[name='unit']">
        <admst:value-of select="attribute[name='unit']/value"/>
	<admst:text format="&quot;(%s)&quot;, "/>
      </admst:when>
      <admst:otherwise>&quot;-&quot;</admst:otherwise>
    </admst:choose>

    <admst:choose>
      <admst:when test="attribute[name='unit']">
        <admst:value-of select="attribute[name='unit']/value"/>
	<admst:text format="&quot;unit&quot; :  &quot;%s&quot;"/>
      </admst:when>
    </admst:choose>
    <admst:text format="},\n"/>
  </admst:if>
</admst:for-each>
</admst:for-each>

<!-- close property array -->
<admst:text format="  ],\n"/>

<!--admst:text format="\n  &quot;tx&quot; = x2 + 4;\n  &quot;ty&quot; = y1 + 4;\n"/-->
<admst:text format="\n  &quot;tx&quot; : 4,\n  &quot;ty&quot; : 4,\n"/>
<admst:text format="  &quot;Model&quot; : &quot;$module&quot;,\n  &quot;NetName &quot; : &quot;T&quot;,\n"/>

<admst:text format="\n\n"/>

<admst:text format="\n  &quot;SymName&quot; : &quot;$module&quot;,\n"/>

<admst:text format="  &quot;BitmapFile&quot; : &quot;$module&quot;,\n"/>

<!-- put in here symbol drawing code and terminal definitions -->
<admst:text format="\n}"/>

<!-- close -->
</admst:open>

<admst:message format="$(module)_props.json: file created\n"/>
</admst>

=== Qucs/qucs/qucs-core/deps/adms/scripts/blockvariables.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
  Usage: admsXml -e blockvariables.xml
  This file illustrates how block variables can be access
  from within the adms data tree.
-->
<!--
  $Id: blockvariables.xml 1102 2008-10-03 14:09:22Z r29173 $
  $Log$
  Revision 1.3  2006/09/04 08:51:05  r29173
  tons of simplifications

  Revision 1.2  2006/03/24 16:49:04  r29173
  updated to adms-2.2.2

  Revision 1.1  2006/03/24 16:36:27  r29173
  initial import

-->

<!DOCTYPE admst SYSTEM "admst.dtd">
<admst version="2.3.0"  xmlns:admst="http://mot-adms.svn.sourceforge.net/viewvc/*checkout*/mot-adms/trunk/adms/admst.dtd">

<admst:template match=":block">
  <admst:choose>
    <admst:when test="adms[datatypename='assignment']">
      <admst:text format="[%(lhs/block/name).%(lhs/name)]"/>
    </admst:when>
    <admst:when test="adms[datatypename='block']">
      <admst:text format="\nblock:%(name) "/>
      <admst:for-each select="variable">
        <admst:text format="%(block/name).%(name)("/>
        <admst:for-each select="probe">%(branch/pnode/name),%(branch/nnode/name)</admst:for-each>
        <admst:text format=") "/>
      </admst:for-each>
      <admst:text format="\n{"/>
      <admst:apply-templates select="item" match=":block"/>
      <admst:text format="}\n"/>
    </admst:when>
  </admst:choose>
</admst:template>
<admst:open file="blockvariables.va">
    `include &quot;disciplines.h&quot;
    module myblockvariable (p,n);
      inout p, n;
      electrical p, n;
      parameter real w=1u;
      parameter real l=1u;
      parameter integer level=0;
      real a1;
      analog
        begin : main
          begin : A
            real a1, a2, a3;
            real b1, b2, b3;
            a1=V(p,n); //A.a1
          end
          a1=1; //myblockvariable.a1
          begin : B
            real a1, a2, a3, a4;
            real b1, b2, b3;
            b1=1; //B.b1
            begin : C
              real a1, a2, a3;
              real b1, b2, b3;
              a2=V(p,n); //C.a2
            end
            a2=V(p,n); //B.a2
          end
          a1=w/l; //myblockvariable.a1
          I(p,n) &lt;+ a1*V(p,n);
        end
    endmodule
</admst:open>
<admst:message format="blockvariables.va: file created\n"/>
<admst:read file="blockvariables.va"/>
<admst:for-each select="/module">
  <admst:apply-templates select="analog/code" match=":block"/>
</admst:for-each> 
</admst>

=== Qucs/qucs/qucs-core/deps/adms/scripts/attributes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE admst PUBLIC "-//adms//DTD admst 2.0//-" "http://mot-adms.sourceforge.net/xml-files/adms/admst.dtd">

<!--
  Usage: admsXml -e attributes.xml
    This example gives some hints on how to use Verilog-AMS attributes.
-->
<!--
  $Id: attributes.xml 1102 2008-10-03 14:09:22Z r29173 $
  $Log$
  Revision 1.1  2006/03/28 13:22:34  r29173
  initial import

  Revision 1.4  2006/03/23 07:51:39  r29173
  fixed bug in computation of ddx

-->

<admst version="2.3.0"  xmlns:admst="http://mot-adms.svn.sourceforge.net/viewvc/*checkout*/mot-adms/trunk/adms/admst.dtd">
  <admst:template match=":attribute">
    <admst:for-each select="attribute">
      <admst:text format="attr: %(name)=%(value)\n"/>
    </admst:for-each> 
    <admst:text format="==============================================\n"/>
  </admst:template>
<admst:open file="attributes.va">
    `include &quot;disciplines.h&quot;
    (* info_before=&quot;module info before&quot; *) module mymodule (p,n) (* info_after=&quot;module info after&quot; *) ;
      (*globalterminal=&quot;my terminals&quot;*) inout p, n;
      electrical p(*localterm=&quot;my p term&quot;*), n(*localterm=&quot;my n term&quot;*);
      (*globalbranch=&quot;my branches&quot;*)branch (p,n) pn;
      (*globalwidth=&quot;width applies to all parameters&quot;*) parameter real w1=1u (*localwidth=&quot;local attribute of width1&quot;*), w2=1u (*localwidth=&quot;local attribute of width2&quot;*);
      (*globallength=&quot;length applies to all parameters&quot;*) parameter real l1=1u (*locallength=&quot;local attribute of length1&quot;*), l2=1u (*locallength=&quot;local attribute of length2&quot;*);
      (*global=&quot;my conductances&quot;*) real g1 (*local=&quot;this is g1&quot;*),g2 (*local=&quot;this is g2&quot;*),g3 (*local=&quot;this is g3&quot;*),g4 (*local=&quot;this is g4&quot;*);
      analog
      begin
        g1=w1/l1;
        g2=w2/l2;
        I(p,n)&lt;+g1*V(p,n) (*contrib_attr1=&quot;hello1&quot; contrib_attr2=&quot;hello2&quot;*);
        I(p,n)&lt;+g2*V(p,n) (*contrib1=&quot;hello1bis&quot; contrib2=&quot;hello2bis&quot; contrib3=&quot;hello3&quot; contrib4=&quot;hello4&quot;*);
      end
    endmodule
</admst:open>
<admst:read file="attributes.va"/>
  <admst:for-each select="/module">
    <admst:apply-templates select="." match=":attribute"/>
    <admst:text format="branch\n"/>
    <admst:for-each select="branch">
      <admst:apply-templates select="." match=":attribute"/>
    </admst:for-each> 
    <admst:text format="node\n"/>
    <admst:for-each select="node">
      <admst:apply-templates select="." match=":attribute"/>
    </admst:for-each> 
    <admst:text format="variable\n"/>
    <admst:for-each select="variable">
      <admst:apply-templates select="." match=":attribute"/>
    </admst:for-each> 
    <admst:text format="contribution\n"/>
    <admst:for-each select="contribution">
      <admst:apply-templates select="." match=":attribute"/>
    </admst:for-each> 
    <admst:text format="source\n"/>
    <admst:for-each select="source">
      <admst:apply-templates select="." match=":attribute"/>
    </admst:for-each> 
  </admst:for-each> 
</admst>

=== Qucs/qucs/qucs-core/deps/adms/scripts/getinstance.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE admst PUBLIC "-//adms//DTD admst 2.0//-" "http://mot-adms.sourceforge.net/xml-files/adms/admst.dtd">
<!--
  Usage: admsXml -e getinstance.xml
  This file prints all instances defined in file <vafile>.
  Note: will work with adms-2.2.2 only - previous versions had bugs :-( 
-->
<!--
  $Id: getinstance.xml 1102 2008-10-03 14:09:22Z r29173 $
  $Log$
  Revision 1.7  2006/03/23 13:46:44  r29173
  cosmetic changes

  Revision 1.4  2006/03/23 07:51:39  r29173
  fixed bug in computation of ddx
-->

<admst version="2.3.0"  xmlns:admst="http://mot-adms.svn.sourceforge.net/viewvc/*checkout*/mot-adms/trunk/adms/admst.dtd">
  <admst:template match=":instance">
    <admst:text format="  %(instantiator/name).%(module/name) #("/>
    <admst:join select="parameterset" separator=", ">
      <admst:text format=".%(parameter)(value)"/>
    </admst:join>
    <admst:text format=") %(name) ("/>
    <admst:join select="terminal" separator=", ">
      <admst:text format="%(nodefrominstantiator/name)"/>
    </admst:join>
    <admst:text format=");\n"/>
  </admst:template>
  <admst:open file="getinstance.va">
    `include &quot;discipline.h&quot;
    module c(ct1,ct2);
      inout      ct1, ct2;
      electrical ct1, ct2;
      parameter real cP1 = 10;
      parameter real cP2 = 10;
      analog
        begin
          I(ct1,ct2)&lt;+V(ct1,ct2)/(cP1+cP2);
        end
    endmodule
    module b(bt1,bt2);
      inout      bt1, bt2;
      electrical bt1, bt2;
      parameter real bP1 = 10;
      parameter real bP2 = 10;
      analog
        begin
          I(bt1,bt2)&lt;+V(bt1,bt2)/bP1;
        end
        c #(.cP1(bP2),.cP2(bP1)) C1(bt1,bt2);
    endmodule
    module a(at1, at2);
      parameter real aP=1.0;
      inout      at1, at2;
      electrical at1, at2;
      electrical topin;
      analog
        begin
          I(at1,at2)&lt;+V(at1,at2)/aP;
        end
        b #(.bP1(aP),.bP2(1/aP)) B1(at1,at2);
        b #(.bP2(aP)) B2(at2,at1);
    endmodule
  </admst:open>
  <admst:read file="getinstance.va"/>
  <admst:message format="getinstance.va: file created\n"/>
  <admst:for-each select="/module">
    <admst:text format="Module: %(name)\n"/>
    <admst:apply-templates select="instance" match=":instance" required="yes"/>
    <admst:text format="\n"/>
  </admst:for-each>
</admst>

=== Qucs/qucs/qucs-core/deps/adms/admsXml/dummy.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE admst SYSTEM "admst.dtd">
<admst version="2.3.0" xmlns:admst="http://mot-adms.sourceforge.net/xml-files/admst">
<admst:template match="print_expression">
  <admst:choose>
    <admst:when test="[datatypename='number']">%(value)%(scalingunit)</admst:when>
    <admst:otherwise>-%(datatypename)-not-done-yet--</admst:otherwise>
  </admst:choose>
</admst:template>
<admst:for-each select="/module">
<admst:variable name="mname" select="%(name)"/>
<admst:message format="build file %(name).net\n"/>
<admst:open file="%(name).net">
<admst:text format="*** Interface: %(/simulator/package_string)\n"/>
<admst:text format="*** created by: %(/simulator/fullname) - %(/simulator/currentdate)\n"/>
<admst:text format="\n"/>
  <admst:text format="* Simple test circuit - automatically created %(/simulator/currentdate) \n"/>
  <admst:text format="\n"/>
  <admst:text format=".options scale=1 gmin=1e-12 reltol=1.0e-8 vabstol=1.0e-08\n"/>
  <admst:text format="\n"/>
  <admst:text format="model my$mname $mname\n"/>
  <admst:for-each select="variable[scope='global_model']">
    <admst:if test="[input='yes']">
      <admst:text format="+ %(name) = %(print_expression(default/tree))\n"/>
    </admst:if>
  </admst:for-each>
  <admst:text format="\n"/>
  <admst:text format="$mname "/>
  <admst:text select="node[location='external']" format="N_$(mname)_%(name)_int "/>
  <admst:text format="my$mname  \n"/>
  <admst:for-each select="variable[scope='global_instance']">
    <admst:if test="[input='yes']">
      <admst:choose>
        <admst:when test="attribute[name='spice:isflag' and value='yes']">
        </admst:when>
        <admst:otherwise>
          <admst:choose>
            <admst:when test="attribute[name='spice:name']">
              <admst:for-each select="attribute[name='spice:name']">
                <admst:text format="+ %(value) = %(print_expression(default/tree))\n"/>
              </admst:for-each>
            </admst:when>
            <admst:otherwise>
              <admst:text format="+ %(name) = %(print_expression(default/tree))\n"/>
            </admst:otherwise>
          </admst:choose>
        </admst:otherwise>
      </admst:choose>
    </admst:if>
  </admst:for-each>
  <admst:text format="\n"/>
  <admst:for-each select="node[location='external']">
    <admst:text format="* inout node \n"/>
    <admst:text format="v_$(mname)_%(name)_vdd N_$(mname)_%(name)_vdd 0 vsource dc=1.0\n"/>
    <admst:text format="r_$(mname)_%(name)1  N_$(mname)_%(name)_int 0 resistor r=1.0\n"/>
    <admst:text format="r_$(mname)_%(name)2  N_$(mname)_%(name)_int N_$(mname)_%(name)_vdd resistor r=1.0\n"/>
  </admst:for-each>
  <admst:text format="\n"/>
  <admst:text format="opPoint dc oppoint=screen print=yes\n"/>
  <admst:text format="* infoall info what=all save=all\n"/>
</admst:open>
</admst:for-each>

</admst>
