=== Qucs/qucs/qucs-core/deps/adms/metaadmst.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
     This dtd describes the basic data structures used by admst classes
     It is used to check the validy of file http://mot-adms/sourceforge.net/xml-files/admst.xml
     You can try using xmllint: xmllint admst.xml -noout -postvalid -noblanks
--> 
<!-- RCS Info -->
<!--
  $Id: metaadmst.dtd 1024 2008-06-10 13:30:21Z r29173 $
-->
<!--
  $Log$
  Revision 1.3  2005/03/22 11:30:18  r29173
  migration to adms-2.x.x: clean-up xml constructs

  Revision 1.2  2005/03/14 17:34:20  r29173
  migration to adms-2.x.x: start xpath coding; add documentation

  Revision 1.1  2005/02/25 11:46:17  r29173
  migration to adms-2.x.x: defines admst namespace

--> 
<!ELEMENT admst (transform)+ >
<!ELEMENT transform (attribute|attribute-implied|attribute-alias|attribute-warning|attribute-obsolete|list|exclude|obsolete|warning)* >
<!ELEMENT xor (attribute|attribute-list)* >
<!ELEMENT attribute EMPTY >
<!ELEMENT attribute-implied EMPTY >
<!ELEMENT attribute-alias EMPTY >
<!ELEMENT attribute-warning EMPTY >
<!ELEMENT attribute-obsolete EMPTY >
<!ELEMENT attribute-list EMPTY >
<!ELEMENT exclude EMPTY >
<!ELEMENT obsolete EMPTY >
<!ELEMENT warning EMPTY >
<!ATTLIST transform name CDATA #REQUIRED haschild CDATA #IMPLIED>
<!ATTLIST attribute name CDATA #REQUIRED type (text|path) "path" >
<!ATTLIST attribute-list name CDATA #REQUIRED type (text|path) "path" >
<!ATTLIST attribute-implied name CDATA #REQUIRED type (text|path) "path" >
<!ATTLIST attribute-warning name CDATA #REQUIRED type (text|path) "path" >
<!ATTLIST attribute-alias alias CDATA #REQUIRED name CDATA #REQUIRED >
<!ATTLIST attribute-obsolete name CDATA #REQUIRED >
<!ATTLIST exclude name CDATA #REQUIRED type (text|path) "path" >
<!ATTLIST obsolete name CDATA #REQUIRED type (text|path) "path" >
<!ATTLIST warning name CDATA #REQUIRED type (text|path) "path" >

=== Qucs/qucs/qucs-core/deps/adms/admst.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="admststyle.xsl"?>
<!DOCTYPE admst SYSTEM "metaadmst.dtd">
<!-- 
       This xml file describes the basic data elements used by admst classes
       its validity is checked by file metaadmst.dtd
       you can try using xmllint: xmllint admst.xml -noout -postvalid -noblanks
       see http://xmlsoft.org/
       Most of the code that builts adms is created automatically from this file
       Note: xsl script admsstyle.xsl transforms the contents of this file to html format 
-->
<!--
  $Id: admst.xml 1163 2008-11-17 17:50:16Z r29173 $
-->
<!--
  $Log$
  Revision 1.9  2005/09/14 15:41:31  r29173
  renamed admst:templates to admst:template (same for apply-template)

  Revision 1.8  2005/08/18 10:45:23  r29173
  renamed admst:choice to admst:choose (admst:choice tolerated)

  Revision 1.7  2005/03/31 18:12:00  r29173
  migration to adms-2.x.x: converted to adms2 syntax

  Revision 1.6  2005/03/22 11:30:18  r29173
  migration to adms-2.x.x: clean-up xml constructs

  Revision 1.5  2005/03/14 17:34:20  r29173
  migration to adms-2.x.x: start xpath coding; add documentation

  Revision 1.4  2005/02/28 09:22:12  r29173
  migration to adms-2.x.x: size renamed count

  Revision 1.3  2005/02/28 08:03:29  r29173
  migration to adms-2.x.x: version required

  Revision 1.2  2005/02/25 14:36:51  r29173
  migration to adms-2.x.x: fixed test vlatovla

  Revision 1.1  2005/02/25 11:46:17  r29173
  migration to adms-2.x.x: defines admst namespace

-->
<admst>
  <transform name="admst">
    <attribute-warning name="version" type="text"/>
  </transform>
  <transform name="admst:for-each">
    <attribute name="select" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="test" type="path"/>
  </transform>
  <transform name="admst:join">
    <attribute name="select" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-implied name="separator" type="text"/>
    <exclude name="test" type="path"/>
  </transform>
  <transform name="admst:break">
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:value-of" haschild="no">
    <attribute name="select" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
  </transform>
  <transform name="admst:if-inside" haschild="yes">
    <attribute name="list" type="text"/>
    <attribute name="select" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
  </transform>
  <transform name="admst:if-not-inside" haschild="yes">
    <attribute name="list" type="text"/>
    <attribute name="select" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
  </transform>
  <transform name="admst:choose">
    <obsolete name="admst:choice"/> 
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="select" type="path"/>
    <exclude name="test" type="path"/>
  </transform>
  <transform name="admst:when">
    <attribute name="test" type="path"/>
    <attribute-implied name="path" type="path"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:otherwise">
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="select" type="path"/>
    <exclude name="test" type="path"/>
  </transform>
  <transform name="admst:if" haschild="yes">
    <attribute name="test" type="path"/>
    <attribute-implied name="path" type="path"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:template">
    <obsolete name="admst:templates"/> 
    <attribute name="match" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-obsolete name="mode"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:apply-templates">
    <obsolete name="admst:apply-template"/> 
    <attribute name="select" type="path"/>
    <attribute name="match" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-implied name="required" type="text"/>
  </transform>
  <transform name="admst:return" haschild="no">
    <attribute name="name" type="text"/>
    <attribute name="string" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-obsolete name="value" new="string"/>
  </transform>
  <transform name="admst:attribute" haschild="yes">
    <attribute name="name" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute name="select" type="path"/>
  </transform>
  <transform name="admst:variable" haschild="no">
    <attribute name="name" type="text"/>
    <xor>
      <attribute name="string" type="text"/>
      <attribute name="select" type="text"/>
      <attribute name="path" type="path"/>
    </xor>
    <attribute-implied name="test" type="path"/>
  </transform>
  <transform name="admst:value-to" haschild="no">
    <attribute name="select" type="path"/>
    <attribute-implied name="string" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-obsolete name="value" new="string"/>
  </transform>
  <transform name="admst:text" haschild="no">
    <attribute-implied name="format" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-implied name="select" type="path"/>
  </transform>
  <transform name="admst:new">
    <attribute name="datatype" type="text"/>
    <xor>
      <attribute-list name="arguments" type="text"/>
      <attribute-list name="inputs" type="path"/>
    </xor>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:push" haschild="no">
    <attribute name="select" type="path"/>
    <attribute name="into" type="path"/>
    <attribute-implied name="onduplicate" type="text"/>
    <attribute-implied name="oncompare" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
  </transform>
  <transform name="admst:reset" haschild="no">
    <attribute name="select" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
  </transform>
  <transform name="admst:count">
    <attribute name="select" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
  </transform>
  <transform name="admst:reverse">
    <attribute name="select" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
  </transform>
  <transform name="admst:read">
    <attribute name="file" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:open">
    <attribute name="file" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:setenv" haschild="no">
    <attribute name="name" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="string" type="text"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:getenv" haschild="no">
    <attribute name="name" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:copy" haschild="no">
    <attribute name="from" type="text"/>
    <attribute name="to" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <exclude name="select" type="path"/>
  </transform>
  <transform name="admst:assert" haschild="no">
    <attribute-implied name="format" type="text"/>
    <attribute name="test" type="path"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="select" type="path"/>
  </transform>
  <transform name="admst:message" haschild="no">
    <attribute name="format" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-implied name="select" type="path"/>
  </transform>
  <transform name="admst:warning" haschild="no">
    <attribute name="format" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-implied name="select" type="path"/>
  </transform>
  <transform name="admst:error" haschild="no">
    <attribute name="format" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-implied name="select" type="path"/>
  </transform>
  <transform name="admst:fatal" haschild="no">
    <attribute name="format" type="text"/>
    <attribute-implied name="path" type="path"/>
    <attribute-implied name="test" type="path"/>
    <attribute-implied name="select" type="path"/>
  </transform>
</admst>
