=== Qucs/qucs/qucs-core/deps/adms/metaadms.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
     This dtd describes the basic data structures used by adms classes
     It is used to check the validy of file http://mot-adms/sourceforge.net/xml-files/adms.xml
     You can try using xmllint: xmllint adms.xml -noout -postvalid -noblanks
--> 
<!--
  $Id: metaadms.dtd 997 2008-05-06 16:36:28Z r29173 $
-->
<!--
  $Log$
  Revision 1.10  2006/09/04 08:51:04  r29173
  tons of simplifications

  Revision 1.9  2005/11/25 14:15:25  r29173
  changed admstpath parser mechanisms

  Revision 1.8  2005/11/22 09:29:47  r29173
  added element comment

  Revision 1.7  2005/05/25 08:27:49  r29173
  moving code from  xmlParserNew.c to xml

  Revision 1.6  2005/03/22 11:30:18  r29173
  migration to adms-2.x.x: clean-up xml constructs

  Revision 1.5  2005/03/17 08:26:28  r29173
  migration to adms-2.x.x: move all href from absolute to relative values

  Revision 1.4  2005/02/25 12:49:35  r29173
  migration to adms-2.x.x: renamed admst transforms

--> 
<!ELEMENT adms (element)+ >
<!ELEMENT element (uid,alias*,(scalar|warning)*,list*,(comment|element)*) >
<!ELEMENT uid (scalar)* >
<!ELEMENT scalar (evalue*) >
<!ELEMENT list EMPTY >
<!ELEMENT reference EMPTY >
<!ELEMENT alias EMPTY >
<!ELEMENT evalue EMPTY >
<!ELEMENT comment (#PCDATA) >
<!ELEMENT warning (#PCDATA) >
<!ATTLIST uid
  format CDATA #REQUIRED
>
<!ATTLIST element
  name CDATA #REQUIRED
  info CDATA #REQUIRED
>
<!ATTLIST scalar
  name CDATA #REQUIRED
  datatypefamily (basicpointer|basictype|reference|adms) "reference"
  datatypename CDATA #REQUIRED
  default CDATA #IMPLIED
  required  (yes|no) "yes"
  info CDATA #REQUIRED
  format CDATA #IMPLIED
>
<!ATTLIST list
  name CDATA #REQUIRED
  datatypefamily (basicpointer|basictype|reference|adms) "reference"
  datatypename CDATA #REQUIRED
  default CDATA #IMPLIED
  required  (yes|no) "yes"
  info CDATA #REQUIRED
  format CDATA #IMPLIED
>
<!ATTLIST alias
  name CDATA #REQUIRED
  element CDATA #REQUIRED
  attribute CDATA #REQUIRED
>
<!ATTLIST evalue
  name CDATA #REQUIRED
  info CDATA #REQUIRED
>

=== Qucs/qucs/qucs-core/deps/adms/adms.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="admsstyle.xsl"?>
<!DOCTYPE adms SYSTEM "metaadms.dtd">
<!-- 
       This xml file describes the basic data elements used by adms classes
       its validity is checked by file metaadms.dtd
       you can try using xmllint: xmllint adms.xml -noout -postvalid -noblanks
       see http://xmlsoft.org/
       Most of the code that builts adms is created automatically from this file
       Note: xsl script admsstyle.xsl transforms the contents of this file to html format 
--> 
<adms>
  <element name="adms" info="base type">
    <uid format="$1">
      <scalar datatypefamily="basictype" name="datatypename" datatypename="basicinteger" info="datatypename" default="@name"/>
    </uid>
    <list datatypefamily="reference" name="attribute" datatypename="attribute" info="list of attribute"/>
    <list datatypefamily="reference" name="variable" datatypename="admstvariable" info="list of variable"/>
    <element name="simulator" info="miscellaneous info on simulator">
      <uid format="$1">
        <scalar datatypefamily="basictype" name="name" datatypename="basicstring" info="name"/>
      </uid>
      <scalar datatypefamily="basictype" name="currentdate" datatypename="basicstring" info="current compilation date"/>
      <scalar datatypefamily="basictype" name="developer" datatypename="basicstring" info="adms version"/>
      <scalar datatypefamily="basictype" name="fullname" datatypename="basicstring" info="full adms version"/>
      <scalar datatypefamily="basictype" name="package_name" datatypename="basicstring" info="autotool package name"/>
      <scalar datatypefamily="basictype" name="package_tarname" datatypename="basicstring" info="autotool package identity"/>
      <scalar datatypefamily="basictype" name="package_version" datatypename="basicstring" info="autotool package version"/>
      <scalar datatypefamily="basictype" name="package_string" datatypename="basicstring" info="autotool package string"/>
      <scalar datatypefamily="basictype" name="package_bugreport" datatypename="basicstring" info="email for bug report"/>
      <warning>dummy variables: should be removed in the future</warning>
      <scalar datatypefamily="reference" name="probe" datatypename="probe" info="dummy variable"/>
      <scalar datatypefamily="basictype" name="tmp" datatypename="basicstring" info="dummy variable" default=""/>
      <scalar datatypefamily="basictype" name="tmp1" datatypename="basicstring" info="dummy variable" default=""/>
      <scalar datatypefamily="reference" name="br1" datatypename="branch" info="dummy variable"/>
      <scalar datatypefamily="reference" name="br2" datatypename="branch" info="dummy variable"/>
      <scalar datatypefamily="reference" name="sr1" datatypename="source" info="dummy variable"/>
      <scalar datatypefamily="basictype" name="ddx" datatypename="basicstring" info="dummy variable" default=""/>
    </element>
    <element name="admsmain" info="adms main pointer - selected using /">
      <uid format="$1">
        <scalar datatypefamily="basictype" name="name" datatypename="basicstring" info="identifier (always admsmain)"/>
      </uid>
      <scalar datatypefamily="basictype" name="argc" datatypename="basicinteger" info="number of command line arguments"/>
      <scalar datatypefamily="basictype" name="fullfilename" datatypename="basicstring" info="full name of veriloga parsed file"/>
      <scalar datatypefamily="basictype" name="filename" datatypename="basicstring" info="base name of veriloga parsed file"/>
      <scalar datatypefamily="basictype" name="curfilename" datatypename="basicstring" info="name of current parsed veriloga file"/>
      <scalar datatypefamily="basictype" name="curline" datatypename="basicinteger" info="current line when parsing file"/>
      <scalar datatypefamily="basictype" name="fpos" datatypename="basicinteger" info="first position of returned parsed token"/>
      <scalar datatypefamily="reference" name="simulator" datatypename="simulator" info="miscellaneous info on simulator"/>
      <scalar datatypefamily="basictype" name="info" datatypename="basicenumeration" info="info mode" default="yes">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="usage" datatypename="basicenumeration" info="usage mode" default="yes">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="verbose" datatypename="basicenumeration" info="verbose mode" default="no">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="hint" datatypename="basicenumeration" info="hint mode" default="no">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="warning" datatypename="basicenumeration" info="warning mode" default="yes">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="obsolete" datatypename="basicenumeration" info="obsolete mode" default="yes">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="debug" datatypename="basicenumeration" info="debug mode" default="no">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="dbg_vla" datatypename="basicenumeration" info="verilogamsparsing debug mode" default="no">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="dbg_xml" datatypename="basicenumeration" info="xml parsing debug mode" default="no">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="error" datatypename="basicenumeration" info="error mode" default="yes">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="fatal" datatypename="basicenumeration" info="fatal mode" default="yes">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <scalar datatypefamily="basictype" name="dbg_mem" datatypename="basicenumeration" info="debug memory mode" default="no">
        <evalue name="yes" info="it is true"/>
        <evalue name="no" info="it is false"/>
      </scalar>
      <list datatypefamily="reference" name="module" datatypename="module" info="list of modules"/>
      <list datatypefamily="reference" name="discipline" datatypename="discipline" info="list of discipline"/>
      <list datatypefamily="reference" name="nature" datatypename="nature" info="list of nature"/>
      <list datatypefamily="reference" name="variable" datatypename="admstvariable" info="global admst variables  (scope is all admst:template)"/>
      <list datatypefamily="basictype" name="argv" datatypename="basicstring" info="command line arguments"/>
      <list datatypefamily="reference" name="transform" datatypename="transform" info="transforms"/>
      <list datatypefamily="reference" name="invtransform" datatypename="transform" info="transforms (inversed order)"/>
      <list datatypefamily="reference" name="itransform" datatypename="itransform" info="instance created by apply-templates"/>
      <list datatypefamily="reference" name="itransforminsideapplytemplate" datatypename="itransform" info="instance inside apply-templates"/>
      <list datatypefamily="reference" name="valueof" datatypename="adms" info="adms stack"/>
    </element>
    <comment>basic adms elements</comment>
    <element name="list" info="adms list">
      <uid format="$1">
        <scalar datatypefamily="basictype" name="datatype" datatypename="basicstring" info="name"/>
      </uid>
      <list datatypefamily="reference" name="item" datatypename="adms" info="item"/>
    </element>
    <comment>elements used to save natures and disciplines inside the internal adms data tree</comment>
    <element name="nature" info="all natures created after parsing">
      <uid format="$1">
        <scalar datatypefamily="basictype" name="access" datatypename="basicstring" info="access identifier"/>
      </uid>
      <scalar datatypefamily="basictype" name="name" datatypename="basicstring" info="name of the nature"/>
      <scalar datatypefamily="reference" name="abstol" datatypename="number" info="absolute tolerance"/>
      <scalar datatypefamily="reference" name="base" datatypename="nature" info="base parent"/>
      <scalar datatypefamily="basictype" name="ddt_name" datatypename="basicstring" info="name of ddt nature"/>
      <scalar datatypefamily="reference" name="ddt_nature" datatypename="nature" info="back to ddt nature"/>
      <scalar datatypefamily="basictype" name="idt_name" datatypename="basicstring" info="name of idt nature"/>
      <scalar datatypefamily="reference" name="idt_nature" datatypename="nature" info="back to idt nature"/>
      <scalar datatypefamily="basictype" name="units" datatypename="basicstring" info="unit"/>
    </element>
    <element name="discipline" info="all disciplines created after parsing">
      <uid format="$1">
        <scalar datatypefamily="basictype" name="name" datatypename="basicstring" info="name of discipline"/>
      </uid>
      <scalar datatypefamily="reference" name="flow" datatypename="nature" info="back to flow nature"/>
      <scalar datatypefamily="reference" name="potential" datatypename="nature" info="back to potential nature"/>
