=== Qucs/qucs/qucs-core/deps/adms/metaadmstpath.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
     This dtd describes the basic data structures used by adms classes
     It is used to check the validy of file http://mot-adms/sourceforge.net/xml-files/admstpath.xml
     You can try using xmllint: xmllint admstpath.xml -noout -postvalid -noblanks
--> 
<!--
  $Id: metaadmstpath.dtd 990 2008-04-29 15:08:06Z r29173 $
-->
<!--
  $Log$
  Revision 1.11  2006/09/13 16:13:19  r29173
  started migration to www.antlr.org tools

  Revision 1.10  2005/12/02 17:48:42  r29173
  cleaned-up admstpath lexical analyzer (lexan)

  Revision 1.9  2005/11/30 13:58:35  r29173
  added nodes maincode and headercode

  Revision 1.8  2005/04/06 08:26:49  r29173
  simplified code

  Revision 1.7  2005/03/31 18:12:01  r29173
  migration to adms-2.x.x: converted to adms2 syntax

  Revision 1.6  2005/03/24 17:39:02  r29173
  migration to adms-2.x.x: moved c-code from perl to xml

  Revision 1.5  2005/03/24 17:03:27  r29173
  migration to adms-2.x.x: fixed bugs in admstpath parser

  Revision 1.4  2005/03/23 13:38:33  r29173
  migration to adms-2.x.x: added xpath parser

  Revision 1.3  2005/03/22 11:30:18  r29173
  migration to adms-2.x.x: clean-up xml constructs

  Revision 1.2  2005/03/17 08:26:28  r29173
  migration to adms-2.x.x: move all href from absolute to relative values

  Revision 1.1  2005/03/16 16:17:17  r29173
  migration to adms-2.x.x: build prerequisites for admst path

  Revision 1.4  2005/02/25 12:49:35  r29173
  migration to adms-2.x.x: renamed admst transforms

--> 

<!ELEMENT admstpath (lex,yacc) >
<!ELEMENT lex (ignore,constant+,regexp+) >
<!ELEMENT constant (#PCDATA) >
<!ELEMENT regexp (#PCDATA) >
<!ELEMENT ignore (#PCDATA) >

<!ATTLIST constant id CDATA #REQUIRED value CDATA #IMPLIED >
<!ATTLIST regexp   id CDATA #REQUIRED >
<!ATTLIST ignore   id CDATA #REQUIRED value CDATA #IMPLIED >

<!ELEMENT yacc (productionset+) >
<!ELEMENT productionset (production+,empty?) >
<!ELEMENT production (item+) >
<!ELEMENT item EMPTY >
<!ELEMENT empty EMPTY >

<!ATTLIST productionset id     CDATA #REQUIRED >
<!ATTLIST productionset ret    CDATA #REQUIRED >
<!ATTLIST item          linkto CDATA #REQUIRED >

=== Qucs/qucs/qucs-core/deps/adms/admstpath.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="admstpathstyle.xsl"?>
<!DOCTYPE admstpath SYSTEM "metaadmstpath.dtd">
<!--
       This XML file describes the basic data elements used by adms classes
       its validity is checked by file metaadms.dtd
       you can try using xmllint: xmllint admstpath.xml -noout -postvalid -noblanks
       see http://xmlsoft.org/
       Most of the code that builds adms is created automatically from this file
       Note: XSL semantic admstpathstyle.xsl transforms the contents of this file to HTML format
-->
<admstpath>

<lex>
  <ignore value="*t&amp;&amp;isspace(*t)" id="space">space - ignored during parsing</ignore>
  <regexp id="openE"><![CDATA[  else if(!strncmp(t,"(",1))
  {
    t+=1, mypparse->_tkid= (admse) tktk_openE;
    paren++;
  }
]]></regexp>
  <regexp id="closeE"><![CDATA[  else if(!strncmp(t,")",1))
  {
    if(PARENMATCH)
    {
      t+=1, mypparse->_tkid= (admse) tktk_closeE, adms_slist_pull(&parenidx);
      adms_slist_pull(&globalctxt);
    }
    else
      t+=1, mypparse->_tkid= (admse) tktk_closeE;
    paren--;
  }
]]></regexp>
  <regexp id="dollarvariable"><![CDATA[  else if(*t=='$'&&*(t+1)=='(')
  {
    t++;
    t++;
    paren++; adms_slist_push(&parenidx,(p_adms)(long)paren); SETTEXT
    mypparse->_tkid= (admse) tktk_dollarvariable;
  }
]]></regexp>
  <regexp id="kdollarvariable"><![CDATA[  else if(*t=='$')
  {
    t++;
    while(isalnum(*t)||*t=='_') t++;
    mypparse->_tkstart=tstart+1;
    mypparse->_tklen=(int)(long)(t-(tstart+1));
    mypparse->_tkid= (admse) tktk_kdollarvariable;
  }
]]></regexp>
  <regexp id="arobavariable"><![CDATA[  else if(*t=='@'&&*(t+1)=='(')
  {
    t++;
    t++;
    paren++; adms_slist_push(&parenidx,(p_adms)(long)paren); SETTEXT
    mypparse->_tkid= (admse) tktk_arobavariable;
  }
]]></regexp>
  <regexp id="karobavariable"><![CDATA[  else if(*t=='@')
  {
    t++;
    while(isalnum(*t)||*t=='_') t++;
    mypparse->_tkstart=tstart+1;
    mypparse->_tklen=(int)(long)(t-(tstart+1));
    mypparse->_tkid= (admse) tktk_karobavariable;
  }
]]></regexp>
  <regexp id="croixcroixvariable"><![CDATA[  else if(*t=='#'&&*(t+1)=='#'&&*(t+2)=='(')
  {
    t++;
    t++;
    t++;
    paren++; adms_slist_push(&parenidx,(p_adms)(long)paren); SETTEXT
    mypparse->_tkid= (admse) tktk_croixcroixvariable;
  }
]]></regexp>
  <regexp id="croixstar"><![CDATA[  else if(*t=='#'&&*(t+1)=='*')
  {
    t++;
    t++;
    while(isalnum(*t)||*t=='_') t++;
    mypparse->_tkstart=tstart+1;
    mypparse->_tklen=(int)(long)(t-(tstart+1));
    mypparse->_tkid= (admse) tktk_croixstar;
  }
]]></regexp>
  <regexp id="kcroixcroixvariable"><![CDATA[  else if(*t=='#'&&*(t+1)=='#')
  {
    t++;
    t++;
    while(isalnum(*t)||*t=='_') t++;
    mypparse->_tkstart=tstart+1;
    mypparse->_tklen=(int)(long)(t-(tstart+1));
    mypparse->_tkid= (admse) tktk_kcroixcroixvariable;
  }
]]></regexp>
  <regexp id="croixvariable"><![CDATA[  else if(*t=='#'&&*(t+1)=='(')
  {
    t++;
    t++;
    paren++; adms_slist_push(&parenidx,(p_adms)(long)paren); SETTEXT
    mypparse->_tkid= (admse) tktk_croixvariable;
  }
]]></regexp>
  <regexp id="kcroixvariable"><![CDATA[  else if(*t=='#')
  {
    t++;
    while(isalnum(*t)||*t=='_') t++;
    mypparse->_tkstart=tstart+1;
    mypparse->_tklen=(int)(long)(t-(tstart+1));
    mypparse->_tkid= (admse) tktk_kcroixvariable;
  }
]]></regexp>
  <regexp id="oquote"><![CDATA[  else if(*t=='\'')
  {
    SETTIC
    t+=1, mypparse->_tkid= (admse) tktk_oquote;
  }
]]></regexp>
  <constant value="!=" id="notequal">Boolean not-equal</constant>
  <constant value="&gt;" id="gt">Boolean gt</constant>
  <constant value="&lt;" id="lt">Boolean lt</constant>
  <constant value="*" id="star">used to select all children</constant>
  <constant value="++" id="incrp">Arithmetic increment</constant>
  <constant value="--" id="incrm">Arithmetic decrement</constant>
  <constant value="+" id="addp">Arithmetic addition</constant>
  <constant value=":" id="column">Arithmetic divide</constant>
  <constant value="," id="comma">comma</constant>
  <constant value="|" id="bar">bar</constant>
  <constant value="-" id="addm">Arithmetic substraction</constant>
  <constant value=".." id="dotdot">selector of previous admst transform</constant>
  <constant value="." id="dot">selector of current admst transform</constant>
  <constant value="/" id="slash">separator between two admstpath items</constant>
  <constant value="=" id="equal">Boolean equal</constant>
  <constant value="[" id="openCond">open admstpath condition</constant>
  <constant value="]" id="closeCond">close admstpath condition</constant>
  <constant value="admst" id="admst">function: return admst element</constant>
  <constant value="and" id="and">Boolean and</constant>
  <constant value="count" id="count">function: return count of argument</constant>
  <constant value="exists" id="exists">function: return 1 if argument is exists</constant>
  <constant value="false" id="false">false() function</constant>
  <constant value="id" id="id">function: generates unique id of argument</constant>
  <constant value="index" id="index">function: return position if second argument inside first argument</constant>
  <constant value="isdefault" id="isdefault">function: return 1 if argument has default value</constant>
  <constant value="lower-case" id="lower_mcase">function: returns argument converted to upper-case string</constant>
  <constant value="nilled" id="nilled">function: return 1 if argument is nilled</constant>
  <constant value="not" id="not">inverse Boolean value of admstpath condition</constant>
  <constant value="or" id="or">Boolean or</constant>
  <constant value="position" id="position">function: return position of argument</constant>
  <constant value="returned" id="returned">function: return value from admst:apply-templates </constant>
  <constant value="reverse" id="reverse">function: reverse order</constant>
  <constant value="sort" id="sort">function: sort in dictionary order</constant>
  <constant value="text" id="text">function: prints first argument using format specified in second argument</constant>
  <constant value="true" id="true">true() function</constant>
  <constant value="uid" id="uid">function: return uid of element</constant>
  <constant value="upper-case" id="upper_mcase">function: returns argument converted to upper-case string</constant>
  <regexp id="ident"><![CDATA[  else if(isalpha(*t))
  {
    while(isalnum(*t)||*t=='_'||*t==':') t++;
    mypparse->_tkid= (admse) tktk_ident;
    mypparse->_tkstart=tstart;
    mypparse->_tklen=(int)(long)(t-tstart);
  }
]]></regexp>
  <regexp id="real integer">  else if(isdigit(*t))
  {
    while(isdigit(*t)) t++;
    if(*t=='.')
    {
      t++;
      while(isdigit(*t)) t++;
      mypparse->_tkid= (admse) tktk_real;
      mypparse->_tkstart=tstart;
      mypparse->_tklen=(int)(long)(t-tstart);
    }
    else
    {
      mypparse->_tkid= (admse) tktk_integer;
      mypparse->_tkstart=tstart;
      mypparse->_tklen=(int)(long)(t-tstart);
    }
  }
</regexp>
</lex>

<yacc>
  <productionset id="root">
    <production id="0">
      <item linkto="pathroot_l"/>
    </production>
    <production id="1">
      <item linkto="goto_atext"/>
      <item linkto="atext"/>
    </production>
  </productionset>
  <productionset id="pathroot_l" ret="path">
    <production id="0">
      <item linkto="pathroot"/>
    </production>
    <production id="1">
      <item linkto="pathroot_l"/>
      <item linkto="comma"/>
      <item linkto="pathroot"/>
    </production>
  </productionset>
  <productionset id="pathroot" ret="path">
    <production id="0">
      <item linkto="pathbar"/>
    </production>
  </productionset>
  <productionset id="pathbar" ret="slist">
   <production id="0">
    <item linkto="pathadd"/>
   </production>
   <production id="1">
    <item linkto="pathbar"/>
    <item linkto="bar"/>
    <item linkto="pathadd"/>
   </production>
  </productionset>
  <productionset id="pathadd" ret="slist">
   <production id="0">
    <item linkto="pathmult"/>
   </production>
   <production id="1">
    <item linkto="pathadd"/>
    <item linkto="addp"/>
    <item linkto="pathmult"/>
   </production>
   <production id="2">
    <item linkto="pathadd"/>
    <item linkto="addm"/>
    <item linkto="pathmult"/>
   </production>
  </productionset>
  <productionset id="pathmult" ret="slist">
   <production id="0">
    <item linkto="pathunary"/>
   </production>
   <production id="1">
    <item linkto="pathmult"/>
    <item linkto="star"/>
    <item linkto="pathunary"/>
   </production>
   <production id="2">
    <item linkto="pathmult"/>
    <item linkto="column"/>
    <item linkto="pathunary"/>
   </production>
  </productionset>
  <productionset id="pathunary" ret="slist">
   <production id="0">
    <item linkto="pathincr"/>
   </production>
   <production id="1">
    <item linkto="addp"/>
    <item linkto="pathincr"/>
   </production>
   <production id="2">
    <item linkto="addm"/>
    <item linkto="pathincr"/>
   </production>
  </productionset>
  <productionset id="pathincr" ret="slist">
   <production id="0">
    <item linkto="pathsep0"/>
   </production>
   <production id="1">
    <item linkto="pathsep0"/>
    <item linkto="incrp"/>
   </production>
   <production id="2">
    <item linkto="pathsep0"/>
    <item linkto="incrm"/>
   </production>
  </productionset>
  <productionset id="pathsep0" ret="slist">
   <production id="0">
    <item linkto="pathsep"/>
   </production>
   <production id="1">
    <item linkto="pathsep"/>
    <item linkto="slash"/>
   </production>
   <production id="2">
    <item linkto="slash"/>
    <item linkto="pathsep"/>
   </production>
   <production id="3">
    <item linkto="slash"/>
    <item linkto="pathsep"/>
    <item linkto="slash"/>
   </production>
  </productionset>
  <productionset id="pathsep" ret="slist">
   <production id="0">
    <item linkto="locationcondition"/>
   </production>
   <production id="1">
